### ISSUE TITLE
Could this query a specific Wunderground PWS?

### ISSUE THREAD

**Issue by Strykar** [ktwilson86/sopel-wunderground#1]
Can I use this to query my PWS? See https://apicommunity.wunderground.com/weatherapi/topics/can-i-get-the-real-time-weather-data-from-a-specific-weather-station

**Comment by ktwilson86** [comment]
Yes! Using this syntax for the .weather query:
.wea[ther] PWS:[PWS ID here]

Also works with .setlocation PWS:[PWS ID here]

Example:
< ktwilson86> .wea PWS:KCASANFR1156
< Willie> Weather for Central SOMA, San Francisco, California: Clear, 64.2 F (17.9 C), 63% humidity, 29.78in (1008mb), Wind From the NW at 2.0 MPH Gusting to 4.5 MPH
